Graphs/Dijkstra/dijkstra.cpp

This PR implements a simple dijkstra algorithm only to educational purpose. Feel free to tell me if has something wrong.

feature(algorithm): add simple dijkstra algorithm

---

Problem Solutions/Codeforces/Tags/sorting/632C.cpp
Problem Solutions/Codeforces/Tags/strings/632C.cpp

CF632C added 

---

Problem Solutions/Codeforces/Tags/implementation/791A.cpp

#13 Solution to #791 for tag -implementation.

Added solution to #791A

---

Problem Solutions/Codeforces/Tags/strings/71A.cpp

Issue #13 , added solution to Question 71A for tag -strings

Added solution to 71A (#13)

---

Problem Solutions/Codeforces/Tags/implementation/990A.cpp

CF 990A added

---

Algorithms/Graphs/MST/prim.cpp

Issue #34 
Graph represented as adjacency matrix

Add Prim's algorithm to find MST (Complexity : O(v^2))

---

Algorithms/Dynamic-Programming/Travelling Salesman Problem.cpp

This pull request adds an implementation for Travelling Salesman Problem.
*Approach Used:* Dynamic Programming, Bit masking
*With reference to:* #60

Add Travelling Salesman Problem.cpp

---

Data Structures/Linked-Lists/RevresingLinkedListTechniques.cpp

Fixed issue #57

---

Data Structures/Linked-Lists/forwardlist_using_stl.cpp
Data Structures/Linked-Lists/list_using_stl.cpp

forward list and list implemented in seperate files.

List implementation using STL #29

---

Data Structures/Array/dynamic_array.cpp

Adding dynamic_array.cpp

---

Algorithms/Balanced_Parenthesis.cpp
Algorithms/Stacks/Balanced_Parenthesis.cpp

Added Balanced_Parenthesis.cpp

---

Algorithms/Graphs/Breadth-First-Search/BFS.cpp
Algorithms/Graphs/Depth-First-Search/DFS.cpp
Algorithms/Graphs/Topological-sorting/topological-sorting.cpp

Add Graph Algorithms

---

Data Structures/Queues/stl_queue.cpp
Data Structures/Stacks/stl_stack.cpp

Added implementation of stack_stl and queue_stl #106

---

Algorithms/Searching/Lower_Bound.cpp
Algorithms/Searching/Upper_Bound.cpp

Added upper bound and lower bound algorithms

---

Data Structures/Queues/stl_priority_queue.cpp

Fixes a subtask of https://github.com/sahilbansal17/Competitive_Coding/issues/106

Added priority_queue

---

Algorithms/Graphs/Floyd-Warshall/floyd_warshall.c

Explanation and code for simple implementation of Floyd-Warshall algorithm

Update Floyd Warshall's algorithm

---

Challenge Problems - GSSoC/islands_in_a_graph.cpp

Added solution to islands in a graph

---

Algorithms/Dynamic-Programming/rod_cutting.cpp

This pull request adds an implementation for Rod Cutting Problem.
Approach Used: Dynamic Programming,
With reference to: #60

Add Rod Cutting Problem.cpp

---

Algorithms/Graphs/Dijkstra/Graph.java
Algorithms/Graphs/Dijkstra/GraphController.java

I have added the solution of Dijkstra's algorithm in Java. Please review.

Added solution of Dijkstra's algorithm

---

Algorithms/Sorting/Quick Sort.cpp

Fixes a subtask of https://github.com/sahilbansal17/Competitive_Coding/issues/48

Added Quick Sort Algorithm

---

Data Structures/Heaps/heap.cpp
Data Structures/Heaps/merging_two_heaps.cpp

Heap data structure operations and merging two heaps

---

Data Structures/Trees/LCA/RMQ.cpp

LCA using RMQ

---

Algorithms/String-Processing/EditDistance.java

I have added the solution of edit distance problem for palindromes.

added solution of edit distance for palindromes

---

Data Structures/Trees/LCA/BinaryLifting.cpp

Binary Lifting for finding LCA

---

Data Structures/matrix_sum_query.cpp

Code for matrix sum query

---

Algorithms/Dynamic-Programming/SubsetSum.java

I have added the solution of the modified subset sum problem.

added solution of modified subset sums

---

Algorithms/Recursion/Chess.java

I have added the solution of issue #186 .

added solution of chess board problem

---

Data Structures/Trees/LCA/NaiveLCA.cpp

Naive approach for finding LCA

---

Algorithms/Sorting/DutchNationalFlag.java

I have added the Dutch national flag algorithm. Issue #197

added dutch national flag algo

---

Algorithms/Sorting/WaveSort.java

I have added the solution of wave sort. Issue #204 .

added wave sort

---

Challenge Problems - GSSoC/pair_sum_problem_BST.cpp

pair_sum_problem_BST

---

Data Structures/Trees/Generic Tree/GenericTree.java
Data Structures/Trees/Generic Tree/GenericTreeClient.java

I have added generic tree implementation and level order traversal of generic tree. Issue #212 .

added generic tree

---

Data Structures/Stacks/infix_to_postfix_Evaluate.cpp

Infix To Postfix Conversion and Evaluation.

---

Algorithms/Sorting/radix_sort.cpp

Add radix_sort

---

Algorithms/Number-Theory/Range Queries/RangeQuery.java

added solution of range query

---

Algorithms/Greedy/Activity_Selection.cpp

Greedy => Activity Selection Problem.

---

Data Structures/Trees/generic_tree.cpp

Generic Tree Implementation with some useful custom functions.

Generic Tree fixed issue #244

---

Algorithms/Greedy/Huffman_Coding.cpp

Adding Huffman Coding Algorithm!

---

Algorithms/Recursion/Print_the_subset_sum_to_K.cpp

implemented the solution to problem.

fixed #207 Print the subset sum to K

---

Data Structures/Array/vector.cpp
Data Structures/Linked-Lists/list.cpp
Data Structures/pair.cpp

@arnav-mandal1234 @vikasgola @ramitsawhney27 please review it

added stl implementation

---

Algorithms/Recursion/PowerSet.cpp

Fixes https://github.com/sahilbansal17/Competitive_Coding/issues/208

added power set

---

Algorithms/String-Matching/NAIVE_STRING_SEARCHING.cpp

Added code for Naive String Matching Algorithm

---

Algorithms/String-Matching/KMP.cpp

KMP algorithm

---

Algorithms/Recursion/retur_subset_sum_to_K.cpp

implement the problem with proper commenting .

fixed Return subsets sum to K(Recursion problem) #258

---

Algorithms/Linked List/linkedlist.java
Data Structures/Linked-Lists/floyd_cycle_detection.java

I have added the solution of issue #265 . Please review @sahilbansal17 @vikasgola

added Floyd's Cycle finding algorithm

---

Algorithms/String-Matching/Rabin-Karp.cpp

Add Rabin-Karp Algorithm

---

Data Structures/Trees/BST_class_implementation.cpp

Implementing Binary Search Tree Class #279

---

Data Structures/Trees/diameter_binary_tree.cpp

Diameter of Binary tree #275

---

Algorithms/Sorting/insertion_sort.cpp

@arnav-mandal1234 please review it

insertion_sort.cpp

---

Data Structures/Heaps/stl_priority_queue.cpp
Data Structures/Heaps/stl_priority_queue_minHeap.cpp

Adding priority_queue as Max & Min Heap

---

Algorithms/Trees/Binary tree/LCA.java

I have added the solution of issue #283

added solution of lca

---

Algorithms/Trees/Binary tree/isBST.java

I have added the solution of issue #288 .

added solution of is BST

---

Algorithms/Trees/Binary tree/printCousins.java

I have added the solution of issue #292 .

added program to print cousins

---

Algorithms/Trees/Binary tree/topView.java

I have added the solution of issue #294 .

added solution of top view of binary tree

---

Algorithms/Searching/sqrt_using_bianry_search.cpp
Algorithms/Sorting/insertion_sort.cpp

@sahilbansal17 @vikasgola @ramitsawhney27 please review

square root using binary search

---

Data Structures/Queues/min_priority_queue.cpp

MinPriority Queue Implementation

---

Data Structures/hashmap_implementation.cpp

HashMap Implementation

---

Algorithms/Dynamic-Programming/Weighted_Job_Scheduling.cpp

*  [x] Fixes #252
* @sahilbansal17 @ramitsawhney27 @vikasgola @arnav-mandal1234 Please Review it.

Weighted Job Scheduling DP

---

Algorithms/Trees/Binary tree/verticalPrint.java

I have added the solution of issue #297 .

added vertical print

---

Data Structures/Trees/largest_BST.cpp

Largest BST

---

Data Structures/Queues/max_priority_queue.cpp

MaxPriority Queue Implementation

---

Algorithms/Linked List/PartitionList.java

I have added the solution of issue #300 .

added solution of partition list

---

Algorithms/Trees/Binary tree/KFar.java

I have added the solution of issue #315 .

added k far

---

Data Structures/Trie/trie.cpp

added remove Word function

---

Algorithms/Dynamic-Programming/EggDroppingPuzzle.java

I have added the solution of issue #325 .

added egg dropping puzzle

---

Algorithms/Linked List/Intersection.java

I have added the solution of issue #338 .

added intersection of linked lists

---

Data Structures/Trie/pattern_matching_with_Trie_DS.cpp

Pattern Matching in Trie Data structure

---

Algorithms/Dynamic-Programming/min_cost_path.cpp

Min Cost Path

---

Algorithms/Linked List/DeleteMiddleNode.java

I have added the solution of issue #340 .

added delete middle node

---

Algorithms/Linked List/SumLists.java

I have added the solution of issue #346 .

added solution of sum lists

---

Algorithms/Dynamic-Programming/min_steps_to_converts_one_sting_to_other.cpp

minimum steps required to make one string equal to other

---

Algorithms/Linked List/Palindrome.java

I have added the solution of issue #351 .

added solution of if linked list is a palindrome

---

Algorithms/Graphs/Graph_using_adjacency_matrix_DFS_BFS_traversal.cpp

 Graph DS implementation using Adjacency Matrix

---

Data Structures/Queues/README.md

Documented the Queue Folder so that it becomes easy to find the required program by users.

Documented the Queue Folder

---

Algorithms/Dynamic-Programming/min_steps_to_1.cpp

Minimum Steps to 1

---

Challenge Problems - GSSoC/islands_in_a_graph_official.cpp

Added the official solution to Islands in a graph. 
Time Complexity: O(n^2)
Space Complexity: O(n^2)
Flood fill based.

Added the official solution to Islands in a graph

---

Challenge Problems - GSSoC/modified_lcs_official.md

Official editorial for the modified LCS problem.

Added the official solution for the modified LCS problem

---

Challenge Problems - GSSoC/modified_fibonacci_official.md

Official editorial for the modified fibonacci problem.

Added the official solution for the modified fibonacci problem

---

Algorithms/Trees/Binary tree/parallel_inorder_bst.go

Added a sample Golang problem that highlights major concepts including:
Algorithms
Channels 
Parallelism

Added a sample Golang problem and it's solution.

---

Data Structures/Stacks/README.md
Data Structures/Trie/README.md

Documented 2 folders i.e Trie DS and Stacks .which helps the users to find their respective programs easily.

Documented Stacks and Trie DS folders

---

README.md

Please review this PR and let me know if any changes required.

README updated for Competitve_Coding repo

---

README.md

Fix #388 
Removes period from the end of checkout command

Remove . from command

---

Problem Solutions/URI/1081.cpp
Problem Solutions/URI/1082.cpp
Problem Solutions/URI/1128.cpp
Problem Solutions/URI/1148.cpp

Those solutions are from the graph category

Some solutions from URI

---

Algorithms/Searching/binary_search.py
Algorithms/Searching/interpolation_search.py
Algorithms/Searching/jump_search.py
Algorithms/Searching/linear_search.py

fixes #391 
added in Algorithms/Searching.
added some search algorithms in python

linear,binary,jump,interpolation Search in python added

---

Data Structures/Linked-Lists/connected.java
Data Structures/Linked-Lists/decimal.java
Data Structures/Linked-Lists/duplicates.java
Data Structures/Linked-Lists/mergelist.java
Data Structures/Linked-Lists/zigzag.java

@sahilbansal17 please review this ! Solves #407 .

linkedlist

---

Algorithms/Searching/binary_search.py
Algorithms/Searching/exponential_search.py
Algorithms/Searching/interpolation_search.py
Algorithms/Searching/jump_search.py
Algorithms/Searching/linear_search.py

Added Exponential Search

---

Algorithms/Stacks/postfix.java
Algorithms/Stacks/prefix.java
Algorithms/Stacks/sort.java

Algo_stack

---

Algorithms/Sorting/bubble_sort.py
Algorithms/Sorting/insertion_sort.py

Fix: #411 Added bubble_sort.py and insertion_sort.py

bubble and insertion sort in Python

---

Algorithms/Stacks/Python/balanced_paranthesis.py
Algorithms/Stacks/Python/postfix_evaluation.py
Algorithms/Stacks/Python/prefix_evaluation.py

includes changes to balanced_paranthesis.py and postfix_evaluation.py (time complexity)

add prefix evaluation using stack Python

---

Algorithms/Stacks/Python/next_greater_element.py

thank you for the suggestion. I have made the necessary changes

modifications to next greater element

---

Problem Solutions/SPOJ/DQUERY.cpp

#431 @sahilbansal17  Have a look

Added solution to spoj problem DQUERY #431

---

Problem Solutions/CodeChef/LTIME76B/ALLSUB.cpp
Problem Solutions/CodeChef/LTIME76B/CATFEED.cpp
Problem Solutions/CodeChef/LTIME76B/PAIRSUM2.cpp
Problem Solutions/CodeChef/LTIME76B/WATCHFB.cpp

Solutions for CodeChef LTIME76B #445

Code Chef LTIME76B Solution #445

---

Algorithms/BitMasking/Check Odd or Even/README.md
Algorithms/BitMasking/Check Odd or Even/check.cpp
Algorithms/BitMasking/Check Power of 2/README.md
Algorithms/BitMasking/Check Power of 2/check_power.cpp
Algorithms/BitMasking/Check ith bit/README.md
Algorithms/BitMasking/Check ith bit/check_ith_bit.cpp
Algorithms/BitMasking/Clear All Bits from MSB/README.md
Algorithms/BitMasking/Clear All Bits from MSB/solution.cpp
Algorithms/BitMasking/Convert Number to Binary/README.md
Algorithms/BitMasking/Convert Number to Binary/convert.cpp
Algorithms/BitMasking/Flip ith bit/README.md
Algorithms/BitMasking/Flip ith bit/flip.cpp
Algorithms/BitMasking/Return First Set Bit/README.md
Algorithms/BitMasking/Return First Set Bit/solution.cpp
Algorithms/BitMasking/Turn Off First Set Bit/README.md
Algorithms/BitMasking/Turn Off First Set Bit/solution.cpp
Algorithms/BitMasking/Turn Off ith bit/README.md
Algorithms/BitMasking/Turn Off ith bit/turn_off_ith_bit.cpp
Algorithms/BitMasking/Turn On ith bit/README.md
Algorithms/BitMasking/Turn On ith bit/turn_on_ith_bit.cpp
Data Structures/Stacks/stack.py

This is the implementation of Stack using Python3 #417

stack implementation in python3

---

Data Structures/Stacks/postfix_to_infix.py

added new file "postfix_to_infix"

---

Algorithms/Number-Theory/Primality-Tests/miller_rabin.py
Algorithms/Other/inversion_count.py

Added the _miller_rabin.py_ file in **/Algorithms/Number-Theory/Primality-Tests** directory and _inversion_count.py_ in **/Algorithms/Other** directory.

Added miller_rabin.py and inversion_count.py

---

Problem Solutions/CodeChef/AUG19B/ MSNSADM1.py

I have added a solution to a problem in August Long Challenge 2019(B), the path to the folder is Problems Solutions/Codechef/AUG19B/MSNSADM1.py

added solution to a problem in august long 19B

---

Algorithms/Number-Theory/SieveOfEratosthenes.java

SieveOfEratosthenes one the efficient algorithm to find the number of a prime number in the given range

SieveOfEratosthenes in java

---

Problem Solutions/HackerRank/Interview Preparation Kit/Knightrv/detect_a_cycle_in_linked_list.cpp
Problem Solutions/HackerRank/Interview Preparation Kit/Knightrv/findmergepoint_of_two_linked_lists.cpp
Problem Solutions/HackerRank/Interview Preparation Kit/Knightrv/inserting_a_node_at_a_specific_position_in_singly_linked_list.cpp
Problem Solutions/HackerRank/Interview Preparation Kit/Knightrv/inserting_a_node_in_sorted_doubly_linked_list.cpp
Problem Solutions/HackerRank/Interview Preparation Kit/Knightrv/reversing_a_doubly_linked_list.cpp

HackerRank interview prep kit ---- Linked list track solutions added
as a participant of Hacktoberfest

Linked List track solution added

---

Data Structures/Linked-Lists/list-implementation.cpp

added palindrome check function and corrected some return types :)

added palindrome check

---

Algorithms/Graphs/Maximum-Flow/maximum-flow-dinic.cpp

Added Maximum Flow solution using Dinic's algorithm. For pull request #375.

Added Maximum Flow Dinic's algorithm problem

---

Problem Solutions/Codeforces/Concept Building Practice/231A.c
Problem Solutions/Codeforces/Concept Building Practice/236A.c

i added 231A and 236A problemset from codeforces in c language

adding 2 problem set question's solution in c language

---

Algorithms/Computational-Geometry/Lines/line_segment_intersection_bentley_ottmann.cpp

- Line sweep/Plane sweep algorithms -
- Point in a polygon problem
- Problem solutions for following problems on SPOJ:
Fixes #370

Added Bentley Ottmann algorithm for line intersection

---

Problem Solutions/Codeforces/Concept Building Practice/900A.cpp

I have added a code for solution 900A of codeforces. It is completely documented for easy understanding of the solution. I would request you to merge this with your project.

Adding solution to Find Extra One (#450)

---

Problem Solutions/CodeChef/LTIME77B/BOXGAME97_soln.py
Problem Solutions/CodeChef/LTIME77B/HIT_soln.py
Problem Solutions/CodeChef/LTIME77B/INVYCNT_soln.py
Problem Solutions/CodeChef/OCT19B/MARM_soln.py
Problem Solutions/CodeChef/OCT19B/S10E_soln.py

I have added the solutions for [S10E](https://www.codechef.com/OCT19B/problems/S10E) and [MARM](https://www.codechef.com/OCT19B/problems/MARM) in Python.

Added solutions of Codechef OCT19B and LTIME77B in Python.

---

Problem Solutions/AtCoder/DP-Contest/B Frog-2.cpp

added solution to Problem B.Frog

---

Problem Solutions/AtCoder/DP-Contest/D Knapsack-1.cpp

added solution to problem D

---

Data Structures/Stacks/stack_paren_balanced.py

added file  stack_balanced parenthesis .
Thanks!

added new file "stck_blnc_paren"

---

Algorithms/Computational-Geometry/Convex-Hull/convex_hull_monotone_chain.cpp

Andrew's monotone chain convex hull algorithm finds the convex hull from a set of 2d points in O(n logn) time.

Add monotone chain in C++

---

Problem Solutions/Codeforces/Southern and Volga Russia Qualifier 2019-2020/B.interesting_vertices.cpp
Problem Solutions/Codeforces/Southern and Volga Russia Qualifier 2019-2020/F.the_number_of_products.cpp
Problem Solutions/Codeforces/Southern and Volga Russia Qualifier 2019-2020/G.swap_lettes.cpp
Problem Solutions/Codeforces/Southern and Volga Russia Qualifier 2019-2020/K.moonbound.cpp
Problem Solutions/Codeforces/Southern and Volga Russia Qualifier 2019-2020/info

https://codeforces.com/gym/102348

added solutions to 4 problems from a contest in cf gym

---

Data Structures/Trie/Trie.Java

Trie Implementation in Java with Display Function

AddingTrieImplementationInJava

---

Problem Solutions/LeetCode/Array/56-Merge-Intervals.cpp

Added Leetcode Problem : 56. Merge Intervals in Arrays

Added Leetcode Problem : 56. Merge Intervals

---

.gitignore
Problem Solutions/CodeChef/OCT19B/MARM.cpp
Problem Solutions/CodeChef/OCT19B/S10E.cpp
Problem Solutions/CodeChef/OCT19B/SAKTAN.cpp

Solutions oct19b

---

Problem Solutions/Codeforces/Concept Building Practice/1244A.c

This piece of code is the solution to the problem 1244A of code forces. It is written in C language with comments inside the code for better understanding.

Solution to the problem 1244A

---

Algorithms/Trees/diameter.cpp
Algorithms/Trees/diameter.py

Tree diameter algorithm in c++ & python

Add tree diameter in cpp & python

---

Problem Solutions/SPOJ/CLOPPAIR.cpp

added solution to geometry problem CLOPPAIR

---

Algorithms/Dynamic-Programming/log_fibonacci.cpp
Algorithms/Dynamic-Programming/log_fibonacci.py
Algorithms/Trees/diameter.cpp
Algorithms/Trees/diameter.py

added logarithmic algorithm for the n-th Fibonacci number

Logarithmic Fibonacci number 

---

Algorithms/Graphs/Bipartite-Graph/bipartite.py

Added bipartite graph check in Python

Add bipartite graph check in python

---

Problem Solutions/CodeChef/APRIL20A/new_method_covid19.cpp

An alternative solution for the COVID problem

Abhayagarwal5 patch 2

---

cpp/number_theory/gcd.cpp

I had to create a new pull request as I had deleted the previous forked version of the repo. So I could not update the previous pull request. I have closed the previous pull request without merging. Thank you.

Add function to find gcd

---

Problem Solutions/HackerRank/Problem Solving/Introduction to Nim Game.cpp
Problem Solutions/HackerRank/Problem Solving/Jim and the orders.cpp
Problem Solutions/HackerRank/Problem Solving/Largest Permutation.cpp
Problem Solutions/HackerRank/Problem Solving/Nimble game.cpp
Problem Solutions/HackerRank/Problem Solving/Poker Nim.cpp

These 5 solutions though not high in difficulty give insight into which type of problems there exists in Greedy and Game Theory
**1.** Introduction to NIM Game **(Game Theory)**
**2.** Jim and the orders **(Greedy)**
**3.** Largest Permutation **(Greedy)**
**4.** Nimble Game **(Game Theory)**
**5.** Poker Nim (**Game Theory)**

Added 5 Solutions of Hackerrank Algorithm Section

---

cpp/array_helper.cpp
cpp/grid_helper.cpp
cpp/main_template.cpp
cpp/number_theory/gcd.cpp

Fixes and additional methods in existing templates
